In [2]:
import pandas as pd
import numpy as np

In [3]:
atp_2003 = pd.read_csv('atp_matches_2003.csv', index_col = 0)
atp_2003

,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
tourney_id,,,,,,,,,,,,,,,,,,,,,
2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,NaN,NaN,Wayne Ferreira,...,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1090.0,42.0,865.0
2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,NaN,Q,Thomas Enqvist,...,NaN,NaN,NaN,NaN,NaN,NaN,146.0,258.0,40.0,950.0
2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,NaN,Q,Jan Michael Gambill,...,NaN,NaN,NaN,NaN,NaN,NaN,57.0,660.0,43.0,855.0
2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,NaN,NaN,Albert Costa,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1170.0,22.0,1190.0
2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,NaN,WC,Alex Corretja,...,NaN,NaN,NaN,NaN,NaN,NaN,127.0,290.0,49.0,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2003-D084,Davis Cup WG PO: SVK vs USA,Clay,4,D,20030919,2,103888,NaN,NaN,Mardy Fish,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1145.0,31.0,1008.0
2003-D084,Davis Cup WG PO: SVK vs USA,Clay,4,D,20030919,4,104053,NaN,NaN,Andy Roddick,...,NaN,NaN,NaN,NaN,NaN,NaN,2.0,4165.0,70.0,531.0
2003-D084,Davis Cup WG PO: SVK vs USA,Clay,4,D,20030919,5,103455,NaN,NaN,Michal Mertinak,...,NaN,NaN,NaN,NaN,NaN,NaN,193.0,193.0,23.0,1145.0
2003-615,Dusseldorf,Clay,64,A,20030519,295,102783,NaN,NaN,Rainer Schuettler,...,NaN,NaN,NaN,NaN,NaN,NaN,11.0,1810.0,81.0,516.0
2003-615,Dusseldorf,Clay,64,A,20030519,288,103454,NaN,NaN,Nicolas Massu,...,NaN,NaN,NaN,NaN,NaN,NaN,84.0,502.0,99.0,400.0

In [5]:
atp_2003.index.nunique()

152

In [6]:
atp_2003.columns

Index(['tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date',
       'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name',
       'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'loser_id',
       'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht',
       'loser_ioc', 'loser_age', 'score', 'best_of', 'round', 'minutes',
       'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms',
       'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn',
       'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced',
       'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points'],
      dtype='object')